✨ rewrite publish logic

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -6,9 +6,16 @@ on:
   workflow_dispatch:
     inputs:
       tag:
-        description: 'Tag to publish'
+        description: '要发布的 Tag'
         required: true
-        default: 'latest'
+        type: string
+        default: 'v1.0.0'
+
+      publish-to-modrinth:
+        description: '是否发布到 Modrinth'
+        required: true
+        type: boolean
+        default: true
 
 jobs:
   build:
@@ -18,15 +25,38 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check changelog
+        id: check_changelog
+        run: |
+          if [ ! -f ./.github/changelog/${{ inputs.tag }}-changelog.md ]; then
+            echo "Changelog file not found"
+            exit 1
+          fi
+
+      - name: Create Tag
+        run: git tag ${{ inputs.tag }}
+        continue-on-error: false
 
       - name: Setup python
         uses: actions/setup-python@v5
         with:
-          python_version: 3.12
+          python-version: 3.12
 
-      - name: Generate Files
+      - name: Generate Zip Files
         run: |
             python3 generate.py
+
+      - name: Generate Changelog
+        run: |
+            git config --global user.name "DreamingLri"
+            git config --global user.email "3507415455@qq.com"
+            git add .
+            git commit -m "📝 auto generate changelog"
+            git push
+        continue-on-error: true
 
       - name: Create Release
         id: create_release
@@ -54,34 +84,41 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: xaeros-map-chinese.zip
-          path: ./xaeros-map-chinese.zip
+          path: |
+            ./xaeros-map-chinese.zip
+            ./.github/changelog/${{ inputs.tag }}-changelog.md
 
   modrinth_publish:
-    name: Publish to Modrinth ${{ github.ref_name }}
+    name: Publish to Modrinth
     runs-on: ubuntu-latest
-    needs: [build]
+    needs: build
+    if: ${{ inputs.publish-to-modrinth }}
 
     steps:
-      - name: Download Release
+
+      - name: Download Artifact
         uses: actions/download-artifact@v4
         with:
           name: xaeros-map-chinese.zip
-      
+
+      - name: Remove 'v' form tag
+        id: remove_v
+        run: |
+          clean_tag="${{ inputs.tag }}"
+          tag="${clean_tag#v}"
+          echo "tag=$tag" >> $GITHUB_ENV 
+
       - name: Publish to Modrinth
         uses: Kir-Antipov/mc-publish@v3.3
         with:
           modrinth-id: VEnCkfVF
-          modrinth-unfeature-mode: subset
-          name: xaero-map-chinese ${{ github.ref_name }}
-          version: ${{ github.ref_name }}
-          version-type: release
-          game-versions: |
-            [1.21, 1.21.3)
-          changelog: |
-            ${{ github.event.release.body }}
-          loaders: minecraft
-          files: |
-            xaeros-map-chinese.zip
           modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
+          name: 1.21+ Xaeros世界地图&小地图汉化-${{ inputs.tag }}
+          version: ${{ env.tag }}
+          version-type: release
+          game-versions: 1.21.x
+          changelog-file: './.github/changelog/${{ inputs.tag }}-changelog.md'
+          files: ./xaeros-map-chinese.zip
+          loaders: minecraft
 
 
